from datetime import datetime


_STATUS = {0: "✓", -1: "–", -2: "⏱"}


def _status_str(rc: int) -> str:
    return _STATUS.get(rc, f"exit {rc}")


def _tools_from_data(data: dict) -> list[tuple[str, str, int, str]]:
    """Return list of (tool_name, lookup_type, returncode, output) tuples."""
    if data.get("type") == "profile":
        rows = []
        for target in data.get("targets", []):
            lt = target["lookup_type"]
            for t in target["tools"]:
                rows.append((t["name"], lt, t["returncode"], t["output"]))
        return rows
    return [
        (t["name"], data.get("type", ""), t["returncode"], t["output"])
        for t in data.get("tools", [])
    ]


def generate_markdown(data: dict) -> str:
    """Generate a GitHub-renderable Markdown report from a result dict."""
    query = data.get("query") or (
        data["targets"][0]["identifier"] if data.get("targets") else "profile"
    )
    lookup_type = data.get("type", "lookup")
    timestamp = data.get("timestamp", "").replace("_", " ")
    tools = _tools_from_data(data)

    lines = [
        f"# iCrackU Report — {lookup_type} — {query}",
        f"**Generated:** {timestamp}",
        "",
        "## Summary",
        "",
        "| Tool | Type | Status | Lines |",
        "|---|---|---|---|",
    ]
    for name, lt, rc, output in tools:
        lines.append(
            f"| {name} | {lt} | {_status_str(rc)} | {len(output.splitlines())} |"
        )

    lines.append("")

    for name, lt, rc, output in tools:
        lines.append(f"## {name}")
        lines.append("")
        lines.append("```")
        lines.append(output)
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def generate_html(data: dict) -> str:
    """Generate a self-contained dark-theme HTML report from a result dict."""
    query = data.get("query") or (
        data["targets"][0]["identifier"] if data.get("targets") else "profile"
    )
    lookup_type = data.get("type", "lookup")
    timestamp = data.get("timestamp", "").replace("_", " ")
    tools = _tools_from_data(data)

    summary_rows = "".join(
        f"<tr><td>{name}</td><td>{lt}</td>"
        f"<td>{_status_str(rc)}</td><td>{len(output.splitlines())}</td></tr>"
        for name, lt, rc, output in tools
    )

    tool_sections = "".join(
        f"<details><summary>{name} <span class='type'>{lt}</span>"
        f" <span class='status'>{_status_str(rc)}</span></summary>"
        f"<pre>{_escape(output)}</pre></details>"
        for name, lt, rc, output in tools
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>iCrackU — {lookup_type} — {_escape(query)}</title>
<style>
  body {{background:#0d0d0d;color:#cccccc;font-family:monospace;padding:2rem;}}
  h1 {{color:#00ff41;border-bottom:1px solid #333;padding-bottom:.5rem;}}
  h2 {{color:#00ff41;margin-top:2rem;}}
  .meta {{color:#555;font-size:.85rem;margin-bottom:2rem;}}
  table {{border-collapse:collapse;width:100%;margin:1rem 0;}}
  th {{text-align:left;border-bottom:2px solid #00ff41;padding:.4rem .8rem;color:#00ff41;}}
  td {{padding:.3rem .8rem;border-bottom:1px solid #1a1a1a;}}
  details {{margin:.5rem 0;background:#1a1a1a;border-left:2px solid #00ff41;}}
  summary {{padding:.5rem 1rem;cursor:pointer;color:#00ff41;}}
  summary:hover {{background:#222;}}
  pre {{padding:1rem;overflow-x:auto;white-space:pre-wrap;word-break:break-all;margin:0;}}
  .type {{color:#555;font-size:.8rem;}}
  .status {{color:#00ff41;}}
  footer {{margin-top:3rem;color:#333;font-size:.8rem;border-top:1px solid #1a1a1a;padding-top:1rem;}}
</style>
</head>
<body>
<h1>iCrackU</h1>
<div class="meta">{lookup_type} &nbsp;·&nbsp; {_escape(query)} &nbsp;·&nbsp; {timestamp}</div>
<h2>Summary</h2>
<table>
  <tr><th>Tool</th><th>Type</th><th>Status</th><th>Lines</th></tr>
  {summary_rows}
</table>
<h2>Results</h2>
{tool_sections}
<footer>Generated by iCrackU &nbsp;·&nbsp; {timestamp}</footer>
</body>
</html>"""


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
